version: 2.1

jobs:
  build:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - checkout

      - restore_cache:
          key:
            v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}

      - run:
          name: Install
          command: poetry install

      - save_cache:
          key:
            v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - 'venv'

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  lint-and-unit-test:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - attach_workspace:
          at: /home/circleci

      - checkout

      - restore_cache:
          key:
            v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}

      - save_cache:
          key:
            v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - 'venv'

      - run:
          name: Linting
          command: poetry run pre-commit run --all-files

      - run:
          name: Unit Test
          command: poetry run tox

      - run:
          name: Coverage
          command: |
            poetry run coverage erase
            poetry run coverage run --source resolver -m pytest
            poetry run coverage xml
            poetry run coverage report --show-missing

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_artifacts:
          path: coverage.xml
          destination: coverage-reports

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  deploy-test:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - run:
          name: Initialise .pypirc
          command: |
            echo -e "[distutils]\n  index-servers =\n    test-pypi\n\n" >> ~/.pypirc
            echo -e "[test-pypi]" >> ~/.pypirc
            echo -e "username: $PYPI_TEST_USER" >> ~/.pypirc
            echo -e "password: $PYPI_TEST_PASSWORD" >> ~/.pypirc
            echo -e "repository: https://test.pypi.org/legacy/" >> ~/.pypirc

      - run:
          name: Create Distribution
          command: |
            poetry build
            poetry run twine check dist/*

      - run:
          name: Upload to PyPi
          command: poetry run twine upload -r test-pypi dist/*

  deploy-production:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - checkout

      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]\n  index-servers =\n    pypi\n\n" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username: $PYPI_PROD_USER" >> ~/.pypirc
            echo -e "password: $PYPI_PROD_PASSWORD" >> ~/.pypirc

      - run:
          name: Create Distribution
          command: |
            poetry build
            poetry run twine check dist/*

      - run:
          name: Upload to PyPi
          command: poetry run twine upload -r pypi dist/*

workflows:
  test:
    jobs:
      - build
      - lint-and-unit-test:
          requires:
            - build
  tag:
    jobs:
      - deploy-test:
          context: sceptre-templates-context
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
      - deploy-production:
          context: sceptre-templates-context
          requires:
            - deploy-test
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
