version: 2.1

jobs:
  build:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: poetry install --extras sceptre -v

      - run:
          name: Run pre-commit
          command: poetry run pre-commit run --all-files

      - run:
          name: Build package
          command: poetry build

      - save_cache:
          key:
            v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}
          paths:
            - '~/.cache/pypoetry'

  tests:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - checkout

      - restore_cache:
          key:
            v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}

      - run:
          name: Unit Tests
          command: poetry run tox

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: htmlcov
          destination: coverage-reports

  deploy-test:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - checkout

      - restore_cache:
          key:
            v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}

      - run:
          name: Initialise .pypirc
          command: |
            echo -e "[distutils]\n  index-servers =\n    test-pypi\n\n" >> ~/.pypirc
            echo -e "[test-pypi]" >> ~/.pypirc
            echo -e "username: $PYPI_TEST_USER" >> ~/.pypirc
            echo -e "password: $PYPI_TEST_PASSWORD" >> ~/.pypirc
            echo -e "repository: https://test.pypi.org/legacy/" >> ~/.pypirc

      - run:
          name: Create Distribution
          command: |
            poetry build
            poetry run twine check dist/*

      - run:
          name: Test upload to PyPi
          command: poetry run twine upload -r test-pypi dist/*

  deploy-prod:
    docker:
      - image: sceptreorg/sceptre-circleci:2.0.0

    steps:
      - checkout

      - restore_cache:
          key:
            v1-dependency-cache-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}

      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]\n  index-servers =\n    pypi\n\n" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username: $PYPI_PROD_USER" >> ~/.pypirc
            echo -e "password: $PYPI_PROD_PASSWORD" >> ~/.pypirc

      - run:
          name: Create Distribution
          command: |
            poetry build
            poetry run twine check dist/*

      - run:
          name: Upload to PyPi
          command: poetry run twine upload -r pypi dist/*

workflows:
  test:
    jobs:
      - build
      - tests:
          requires:
            - build
  tag:
    jobs:
      - deploy-test:
          context: sceptre-templates-context
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
      - deploy-prod:
          context: sceptre-templates-context
          requires:
            - deploy-test
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
